name: bookingcar

services:
  backend:
    image: bookingcar-backend
    build:
      context: .
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - bookingcar-net

  postgres:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=booking_car
    ports:
      - "5433:5432"
    networks:
      - bookingcar-net
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - bookingcar-net
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  bookingcar-net:
    driver: bridge

volumes:
  db-data:
  pgadmin-data: