spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/booking_car
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        highlight_sql: false
        hbm2ddl.auto: validate
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  image:
    bucket: "/app/images"

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
